### ISSUE TITLE
Is there a way to get req.url in the plugin

### ISSUE THREAD

**Issue by JohnMcLear** [luto/ep_defaultPadText#7]

**Comment by luto** [comment]
Not possible because EPL does not know its external address (if it is behind a NAT or reverse-proxy, for example). Adding a special setting for this URL would be kinda pointless because you can just do:

``` javascript
"meeting" : {
  "text": "http://beta.etherpad.org/p/meeting$num$"
}
```

which gives you this pads URL in the pad-text.
